# -- Theme Options --
# These options control how the theme functions and allow you to customize the display of your website.
# Refer to the theme docs for more details about each of these parameters.
# https://mnjm.github.io/kayal/docs/configuration/#theme-parameters

# [Optional] Path to the site logo image relative to assets/ folder. Displayed before the Site Title in the header. Minimum size: 64x64px.
logo = "/imgs/logo.png"
# Site description.
description = "A Hugo Theme"
# [Optional] Copyright owner name.
copyright = "Sowndarya Krishnan Navaneetha Kannan"
# Whether to optimize images per view port.
optimizeImg = true
# Whether to enable copy button in code blocks.
enableCodeCopy = true
# Show the icon that switches between dark and light themes when clicked.
showThemeSwitcher = true
# Default theme to start from. If "auto", it detects the previous preference/system theme.
defaultTheme = "auto"  # Valid Options: light, dark, auto
# When enabled, highlight the current menu item in the menu bar.
highlightCurrentMenu = true
# The sections to display in the recent articles list. If not provided, the section with the most articles is used.
mainSections = ["posts"]
# Whether to remove Hugo and theme attribution in the footer.
removeAttribution = true
# Whether to show anchor links in headings. Can be overridden by Page-specific `showHeadingAnchors` in its front matter.
showHeadingAnchors = true
# Whether to enable search. Needs JSON output for this to work.
enableSearch = true


# Site search engine verification tags.
# [verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
# paginate = 4 
# Homepage settings
[homepage]

# Whether to show recent items on the homepage.
showRecent = true
# Heading label for recent items.
showRecentLabel = "Recent Posts"
# Number of recent items to show.
showRecentItems = 2
# Whether to display a "Show more" link at the end of recent section that directs to `showMoreDest`.
showMore = true
showMoreDest = "/posts"
[homepage.profile]
# [Optional] Displayed at the top of your homepage.
# headline = "👋 Welcome to my site"
# [Optional] Path to the profile image relative to assets/ folder. Minimum size: 200x200px.
# image = "imgs/profile.svg"
# Image position.
where = "right"  # Options: right, left, top


 # This will show 4 updates per page


# Article settings
[article]
# Whether to display article dates.
showDate = false
# Whether to display modified dates of articles.
showModDate = true
# Whether to display reading time of articles.
showReadingTime = true
# Whether to display tags mentioned in the front matter.
showTags = true
# Whether to display next/previous article links in the article footer.
showPagination = false
# Whether to reverse the direction of next/previous article links.
invertPagination = true
# Whether to display the table of contents on articles.
showToC = true
# Whether to open the Table of Contents when the page is loaded.
openToC = false
# Check https://mnjm.github.io/kayal/docs/advanced-customization/#comments
showComments = false
# Whether to display breadcrumbs
showBreadcrumbs = true

# List template settings
[list]
# Whether to group articles by year.
groupByYear = false
# Whether to display breadcrumbs
showBreadcrumbs = true
# Whether to display pages as a card
cardView = true
# Whether to display RSS link
showRSS = true

# Taxonomy settings
[taxonomy]
# Whether to show counts of each taxonomy term.
showCount = true
# Whether to display taxonomies as a grid of cards.
cardView = true
headline = "Krish"
# Term settings
[term]
# Whether to group articles by year.
groupByYear = false
# Whether to display breadcrumbs
showBreadcrumbs = true
# Whether to display pages as a card
cardView = true
# Whether to display RSS link
showRSS = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

